### ISSUE TITLE
Possible source of crashes due to non-homebrew librsvg

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#14]
I'm seeing a conflict with Fink that may produce crashes when using `print` for `saves`.

```
==> Installing imagemagick dependency: librsvg
==> Downloading https://download.gnome.org/sources/librsvg/2.40/librsvg-2.40.15.tar.xz
==> Downloading from http://ftp.cse.buffalo.edu/pub/Gnome/sources/librsvg/2.40/librsvg-2.40.15.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/Applications/Octave.app/Contents/Resources/usr/Cellar/librsvg/2.40.15 --disable-Bsymbolic --enable-tools=yes --enable-pixbuf-loader=yes --enable-introspection=yes
==> make install gdk_pixbuf_binarydir=/Applications/Octave.app/Contents/Resources/usr/Cellar/librsvg/2.40.15/lib/gdk-pixbuf-2.0/2.10.0/loaders gdk_pixbuf_moduledir=/Applications/Octave.app/Contents/Resour
Last 15 lines from /Users/bpabbott/Library/Logs/Homebrew/librsvg/02.make:
  CC       librsvg_2_la-rsvg-file-util.lo
  CC       librsvg_2_la-rsvg-size-callback.lo
  CC       librsvg_2_la-rsvg-xml.lo
  CC       rsvg_convert-rsvg-convert.o
  CC       rsvg_convert-rsvg-size-callback.o
  CC       librsvg_2_la-librsvg-enum-types.lo
  CCLD     librsvg-2.la
  CCLD     rsvg-convert
  GISCAN   Rsvg-2.0.gir
  GICOMP   Rsvg-2.0.gir
Could not find GIR file 'GdkPixbuf-2.0.gir'; check XDG_DATA_DIRS or use --includedir
error parsing file Rsvg-2.0.gir: Failed to parse included gir GdkPixbuf-2.0
make[2]: *** [Rsvg-2.0.typelib] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /Applications/Octave.app/Contents/Resources/usr/Library/Homebrew/utils.rb:618:in `open'
	from /Applications/Octave.app/Contents/Resources/usr/Library/Homebrew/utils.rb:651:in `issues_matching'
	from /Applications/Octave.app/Contents/Resources/usr/Library/Homebrew/utils.rb:683:in `issues_for_formula'
	from /Applications/Octave.app/Contents/Resources/usr/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /Applications/Octave.app/Contents/Resources/usr/Library/Homebrew/exceptions.rb:218:in `issues'
	from /Applications/Octave.app/Contents/Resources/usr/Library/Homebrew/exceptions.rb:263:in `dump'
	from /Applications/Octave.app/Contents/Resources/usr/Library/brew.rb:133:in `rescue in <main>'
	from /Applications/Octave.app/Contents/Resources/usr/Library/brew.rb:29:in `<main>'
```

Might the suggestion ...

`Could not find GIR file 'GdkPixbuf-2.0.gir'; check XDG_DATA_DIRS or use --includedir
`

allow this problem to be avoided?

**Comment by schoeps** [comment]
I think this is only a warning and I will remove the hard dependency on imagemagick anyhow. It was only necessary for icon conversion (svg->png).
