### ISSUE TITLE
broken script

### ISSUE THREAD

**Issue by bpabbott** [schoeps/octave_installer#22]
When I pulled today, there were 95 changes.

```
$ git pull
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 2), reused 2 (delta 2), pack-reused 1
Unpacking objects: 100% (6/6), done.
From https://github.com/schoeps/octave_installer
   a930be6..ad82ec5  master     -> origin/master
Updating a930be6..ad82ec5
Fast-forward
 install_octave.sh | 95 ++++++++++++++++++++++++++++++++++++++-----------------
 1 file changed, 66 insertions(+), 29 deletions(-)
```
Running the script quickly failed.

```
$ ./install_octave.sh 
Create new homebrew installation in /Applications/Octave.app.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0    181      0 --:--:-- --:--:-- --:--:--   181
100   139    0   139    0     0    187      0 --:--:-- --:--:-- --:--:--   187
100  194k  100  194k    0     0  72247      0  0:00:02  0:00:02 --:--:--  187k
./install_octave.sh: line 120: ./brew: No such file or directory
./install_octave.sh: line 121: ./brew: No such file or directory
./install_octave.sh: line 122: ./brew: No such file or directory
Error: Unknown command: install
Error: Unknown command: install
==> Tapping homebrew/science
Cloning into '/Applications/Octave.app/Contents/Resources/usr/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 606, done.
remote: Compressing objects: 100% (604/604), done.
remote: Total 606 (delta 1), reused 73 (delta 0), pack-reused 0
Receiving objects: 100% (606/606), 519.06 KiB | 759.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
Checking out files: 100% (602/602), done.
Tapped 593 formulae (625 files, 1.6M)
Error: Unknown command: install
Error: Unknown command: install
./install_octave.sh: line 149: ./gs: No such file or directory
Did not find Aquaterm; build gnuplot without it.
Error: Unknown command: install
Error: Unknown command: install
Error: Unknown command: install
Error: Unknown command: install
Error: Kernel.exit
Error: Unknown command: install
Error: Unknown command: install
Error: Unknown command: install
Error: Unknown command: install
/Applications/Octave.app/Contents/Resources/usr/Library/brew.rb:114:in `exit'
/Applications/Octave.app/Contents/Resources/usr/Library/brew.rb:114:in `<main>'
./install_octave.sh: line 207: ./octave: No such file or directory
./install_octave.sh: line 208: ./octave: No such file or directory
./install_octave.sh: line 209: ./octave: No such file or directory
Error: Unknown command: uninstall
Error: Unknown command: install
./install_octave.sh: line 221: [: missing `]'
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/16x16/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/32x32/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/32x32/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/64x64/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/128x128/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/256x256/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/256x256/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/512x512/apps/octave.png: No such file or directory
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/share/icons/hicolor/512x512/apps/octave.png: No such file or directory
/tmp/iconset-ADaW/droplet.iconset:error: Iconset contains no image resources.
/tmp/iconset-ADaW/droplet.iconset:error: Failed to generate ICNS.
Unable to set file icon
Cloning into '/tmp/octave-OJT5/create-dmg'...
remote: Counting objects: 191, done.
remote: Total 191 (delta 0), reused 0 (delta 0), pack-reused 191
Receiving objects: 100% (191/191), 44.43 KiB | 0 bytes/s, done.
Resolving deltas: 100% (98/98), done.
Checking connectivity... done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  224k  100  224k    0     0   186k      0  0:00:01  0:00:01 --:--:--  186k
Creating disk image...
..............................................................................
created: /Users/bpabbott/rw.Octave-Installer.dmg
Mounting disk image...
Unmounting disk image...
Mount directory: /Volumes/Octave-Installer
Device name:     /dev/disk8
Copying background file...
making link to Applications dir
/Volumes/Octave-Installer
Copying volume icon file '/Applications/Octave.app/Contents/Resources/applet.icns'...
Copying custom files...
/Applications/Octave.app/Contents/Resources/usr/opt/octave/COPYING
cp: /Applications/Octave.app/Contents/Resources/usr/opt/octave/COPYING: No such file or directory
DMG ready: /Users/bpabbott/Octave-Installer.dmg
```

**Comment by bpabbott** [comment]
Qualification: I deleted `/Applications/Octave.app` before running the script.

**Comment by bpabbott** [comment]
brew is where it should be.
```
$ ls /Applications/Octave.app/Contents/Resources/usr/bin/
brew
```

**Comment by bpabbott** [comment]
I'll report back later when the script completes, but the change below looks to have resolved the problem.
```
diff --git a/install_octave.sh b/install_octave.sh
index 3a3ad8d..73dd3ba 100755
--- a/install_octave.sh
+++ b/install_octave.sh
@@ -115,6 +115,7 @@ else
        osacompile -o "$install_dir" -e " "
        mkdir -p "$install_dir/Contents/Resources/usr"
        curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C "$install_dir/Contents/Resources/usr"
+       cd "$install_dir/Contents/Resources/usr/bin"
 fi
```
